POST http://localhost:5000/comment/1 HTTP/1.1
content-type: multipart/form-data; boundary=----boundary
Cookie: session=eyJjc3JmX3Rva2VuIjoiY2E4ODUxYWFjZmRmMmQ0YjRlNDkyNDFiOWYzNDg1NDEiLCJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6ImJvYiJ9.ZQwr4g.wftSLVCuOfxy2GZ9MZLWNAgbqL8

------boundary
Content-Disposition: form-data; name="comment"

Yes I am Bob
------boundary--
